FROM tomcat:8.5

CMD mkdir /usr/local/tomcat/ROOT/ \
    && cp -r /tmp/artifacts/*.war /usr/local/tomcat/ROOT/index.war \
    && cp /tmp/artifacts/*/Config.properties /usr/local/tomcat/ROOT/Config.properties \
    && /usr/local/tomcat/bin/catalina.sh run